name: Validate AZD template
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "infra/**"
  pull_request:
    branches: [ main ]
    paths:
      - "infra/**"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Build Bicep for linting
        uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
        with:
          inlineScript: az config set bicep.use_binary_from_path=false && az bicep build -f infra/main.bicep --stdout
          
      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@6f5948dfacef28e207b48d0905cf90c03365536d # v3.37.9
        if: github.repository == 'Azure-Samples/azure-search-openai-demo-csharp'
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}